pipeline {
    agent any

    environment {
        IMAGE_NAME = "sridharsri102004/dvp-app"
    }

    stages {

        stage('Build & Test') {
            steps {
                sh '''
                python3 --version
                pip3 install --user -r dvp-week12-app/requirements.txt
                python3 -m pytest dvp-week12-app
                '''
            }
        }

        stage('Docker Build') {
            steps {
                sh '''
                docker build -t $IMAGE_NAME dvp-week12-app
                '''
            }
        }

        stage('Docker Login & Push') {
            steps {
                withCredentials([usernamePassword(
                    credentialsId: 'dockerhub',
                    usernameVariable: 'USER',
                    passwordVariable: 'PASS'
                )]) {
                    sh '''
                    echo $PASS | docker login -u $USER --password-stdin
                    docker push $IMAGE_NAME
                    '''
                }
            }
        }

        stage('Run Container') {
            steps {
                sh '''
                docker run -d -p 5000:5000 $IMAGE_NAME
                '''
            }
        }
    }
}
